# -*- coding: utf-8 -*-

##
#  @file gui.py
#  Файл, сгенерированный PyQt5.
#  Этот файл содержит класс Ui_MainWindow, который используется для управления интерфейсом пользователя.
#
#  Внимание: Любые ручные изменения в этом файле будут потеряны при следующем запуске pyuic5.
#  Не редактируйте этот файл, если вы не знаете, что делаете.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


## Класс, генерируемый PyQt5 из файла .ui, определяющий интерфейс пользователя.
#  Этот класс содержит автоматически сгенерированные методы и атрибуты для управления
#  виджетами в главном окне приложения, такие как кнопки, поля ввода, метки и графические элементы.
class Ui_MainWindow(object):
    ## Инициализирует элементы интерфейса пользователя и устанавливает основные параметры виджетов.
    #  @param MainWindow Основное окно приложения, в котором размещаются все виджеты.
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 709)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.EntryLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntryLabel.sizePolicy().hasHeightForWidth())
        self.EntryLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EntryLabel.setFont(font)
        self.EntryLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EntryLabel.setObjectName("EntryLabel")
        self.verticalLayout_4.addWidget(self.EntryLabel)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.DistLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DistLabel.setFont(font)
        self.DistLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DistLabel.setObjectName("DistLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.DistLabel)
        self.DistComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DistComboBox.setObjectName("DistComboBox")
        self.DistComboBox.addItem("")
        self.DistComboBox.addItem("")
        self.DistComboBox.addItem("")
        self.DistComboBox.addItem("")
        self.DistComboBox.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DistComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.LowerBoundLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LowerBoundLabel.setFont(font)
        self.LowerBoundLabel.setObjectName("LowerBoundLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LowerBoundLabel)
        self.LowerBoundLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LowerBoundLineEdit.setObjectName("LowerBoundLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LowerBoundLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.UpperBoundLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UpperBoundLabel.setFont(font)
        self.UpperBoundLabel.setObjectName("UpperBoundLabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.UpperBoundLabel)
        self.UpperBoundLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UpperBoundLineEdit.setObjectName("UpperBoundLineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.UpperBoundLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.SizeLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SizeLabel.setFont(font)
        self.SizeLabel.setObjectName("SizeLabel")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.SizeLabel)
        self.SizeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SizeLineEdit.setObjectName("SizeLineEdit")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.SizeLineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.BandwithLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BandwithLabel.setFont(font)
        self.BandwithLabel.setObjectName("BandwithLabel")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.BandwithLabel)
        self.BandwithLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.BandwithLineEdit.setInputMask("")
        self.BandwithLineEdit.setObjectName("BandwithLineEdit")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.BandwithLineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.IntervalsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IntervalsLabel.sizePolicy().hasHeightForWidth())
        self.IntervalsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IntervalsLabel.setFont(font)
        self.IntervalsLabel.setObjectName("IntervalsLabel")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.IntervalsLabel)
        self.IntervalsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.IntervalsLineEdit.setObjectName("IntervalsLineEdit")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.IntervalsLineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_4.setItem(11, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.CalcButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalcButton.sizePolicy().hasHeightForWidth())
        self.CalcButton.setSizePolicy(sizePolicy)
        self.CalcButton.setObjectName("CalcButton")
        self.verticalLayout_4.addWidget(self.CalcButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CDFGraphLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CDFGraphLabel.setFont(font)
        self.CDFGraphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CDFGraphLabel.setObjectName("CDFGraphLabel")
        self.verticalLayout.addWidget(self.CDFGraphLabel)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.CDFGraphWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CDFGraphWidget.sizePolicy().hasHeightForWidth())
        self.CDFGraphWidget.setSizePolicy(sizePolicy)
        self.CDFGraphWidget.setObjectName("CDFGraphWidget")
        self.verticalLayout.addWidget(self.CDFGraphWidget)
        self.CDFGraphWidget.setBackground('w')
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.PDFGraphLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PDFGraphLabel.setFont(font)
        self.PDFGraphLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PDFGraphLabel.setObjectName("PDFGraphLabel")
        self.verticalLayout.addWidget(self.PDFGraphLabel)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.PDFGraphWidget = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PDFGraphWidget.sizePolicy().hasHeightForWidth())
        self.PDFGraphWidget.setSizePolicy(sizePolicy)
        self.PDFGraphWidget.setObjectName("PDFGraphWidget")
        self.verticalLayout.addWidget(self.PDFGraphWidget)
        self.PDFGraphWidget.setBackground('w')
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    ## Устанавливает текстовые метки интерфейса, переводит интерфейс на текущий язык пользователя.
    #  @param MainWindow Основное окно приложения, текстовые метки которого нужно обновить.
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EntryLabel.setText(_translate("MainWindow", "Параметры распределения"))
        self.DistLabel.setText(_translate("MainWindow", "Распределение:"))
        self.DistComboBox.setItemText(0, _translate("MainWindow", "Нормальное распределение"))
        self.DistComboBox.setItemText(1, _translate("MainWindow", "Равномерное распределение"))
        self.DistComboBox.setItemText(2, _translate("MainWindow", "Экспоненциальное распределение"))
        self.DistComboBox.setItemText(3, _translate("MainWindow", "Распределение Лапласа"))
        self.DistComboBox.setItemText(4, _translate("MainWindow", "Распределение Коши"))
        self.LowerBoundLabel.setText(_translate("MainWindow", "Нижняя граница:"))
        self.LowerBoundLineEdit.setText(_translate("MainWindow", "0"))
        self.UpperBoundLabel.setText(_translate("MainWindow", "Верхняя граница:"))
        self.UpperBoundLineEdit.setText(_translate("MainWindow", "1"))
        self.SizeLabel.setText(_translate("MainWindow", "Объём выборки:"))
        self.SizeLineEdit.setText(_translate("MainWindow", "100"))
        self.BandwithLabel.setText(_translate("MainWindow", "Размытость:"))
        self.BandwithLineEdit.setText(_translate("MainWindow", "0.5"))
        self.IntervalsLabel.setText(_translate("MainWindow", "Кол-во интервалов:"))
        self.IntervalsLineEdit.setText(_translate("MainWindow", "20"))
        self.CalcButton.setText(_translate("MainWindow", "Провести оценку"))
        self.CDFGraphLabel.setText(_translate("MainWindow", "Функция распределения"))
        self.PDFGraphLabel.setText(_translate("MainWindow", "Плотность распределения"))

